version: '3'

services:
  database:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d INFOM126 -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  back-end:
    container_name: back-end
    build:
      context: './back-end'
      dockerfile: 'Dockerfile'
    ports:
      - '5000:5000'
    depends_on:
      database:
        condition: service_healthy

  front-end:
    container_name: front-end
    build:
      context: './front-end'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    depends_on:
      - back-end
