# docker compose file for development environment

version: '3'

services:
  database:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  back-end:
    container_name: back-end
    build:
      context: './back-end'
      dockerfile: 'Dockerfile'
    ports:
      - '5000:5000'
    environment:
      DB_HOST: database
      DB_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      database:
        condition: service_healthy

  front-end:
    container_name: front-end
    build:
      context: './front-end'
      dockerfile: 'Dockerfile'
      args:
        VITE_API_HOST: ${HOST_ADDRESS}
        VITE_API_PORT: 5000
    ports:
      - '80:80'
    depends_on:
      - back-end
